# Site Information
site_name: Zelda 64 Custom Music Wiki
site_url: https://bombchus.github.io/z64-music-wiki/
site_description: >-
  Documentation and resources for creating custom music for Ocarina of Time and
  Majora's Mask to be used in conjunction with the OOT, MM, and OOTMM Randomizers

# Repository Information
#repo_name: bombchus/z64-music-wiki
#repo_url: https://github.com/bombchus/z64-music-wiki

# Copyright Information
copyright: |
  Copyright &copy; 2024 <a href="https://github.com/bombchus" target="_blank" rel="noopener">Bombchus</a>

# Config
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.indexes
    #- navigation.path
    - navigation.expand
    - navigation.top
    - navigation.footer
    #- toc.integrate
    #- toc.follow
    - search.suggest
    - search.highlight
    #- content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: en
  palette:

    # light mode, automatically assigned by default to users with light OS theme
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
      primary: deep purple
      accent: deep purple

    # dark mode, automatically assigned by default to users with dark OS theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
      primary: deep purple
      accent: deep purple

# Additional Config
extra:
  social:
    #- icon: fontawesome/brands/discord
      #link: https://discord.gg/ootrandomizer
      #name: Ocarina of Time Randomizer Discord
    #- icon: fontawesome/brands/discord
      #link: https://discord.gg/7jBRhhJ
      #name: Majora's Mask Randomizer Discord
    #- icon: fontawesome/brands/discord
      #link: https://discord.gg/4QdtPBP6wf
      #name: OOTMM Randomizer Discord
    #- icon: fontawesome/brands/bluesky
      #link: https://bsky.app/profile/bombchus.bsky.social
      #name: Bluesky

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
        - includes/links.md
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# Plugins
plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: bombchus/z64-music-wiki
      branch: main
  #- git-authors
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox:
      effect: zoom
      draggable: false
      background: none
      shadow: false
      manual: true

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css

# Page Tree
nav:
  - Home: index.md
  - Getting Started:
    - Requirements: requirements.md
  - Basic:
    - rename: basic/rename.md
  - Advanced:
    - Tuning: advanced/tuning.md
    - Formmask: advanced/formmask.md
    - ADSR:
      - Custom Envelopes: advanced/adsr/envelopes.md
      - Audiobank Envelopes: advanced/adsr/abenvelope.md
      - Sequence Envelopes: advanced/adsr/seqenvelope.md
    - Custom Sample Injection:
      - Injection Overview: advanced/sampling/overview.md
    - MIDI:
      - Advanced MIDI Overview: advanced/midi/overview.md
  - Vanilla References:
    - Audiobank Reference: vanilla-reference/audiobanks.md
    - Sample Reference: vanilla-reference/samples.md
    - Sequence Commands: vanilla-reference/seq-commands.md